/* Header file for function TestFunction
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void testfunction_startup(void);

/* Provided interfaces */
void testfunction_PI_trigger( void );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
