/* Body file for function Receiver
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "receiver.h"
#include <stdio.h>


void receiver_startup(void)
{
   printf("[Receiver] Startup\n");
}

void receiver_PI_ping
      (const asn1SccDataItem *IN_param)

{
   printf("[Receiver] Received ping with value %ld\n", *IN_param);
}


