/* Header file for function Receiver
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void receiver_startup(void);

/* Provided interfaces */
void receiver_PI_ping( const asn1SccDataItem * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
