/* Body file for function Sender
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "sender.h"



void sender_startup(void)
{
   printf("[Sender] Startup\n");
}

void sender_PI_trigger(void)
{
   static asn1SccDataItem item = 0;
   item++;
   sender_RI_ping(&item);
}


