/* Header file for function Sender
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void sender_startup(void);

/* Provided interfaces */
void sender_PI_trigger( void );

/* Required interfaces */
extern void sender_RI_ping( const asn1SccDataItem * );


#ifdef __cplusplus
}
#endif
