/* Body file for function TestFunction
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "testfunction_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void testfunction_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned testfunction_initialized = 0;
void init_testfunction(void)
{
   if (0 == testfunction_initialized) {
      testfunction_initialized = 1;
      // Call user code startup function
      extern void testfunction_startup(void);
      testfunction_startup();
      testfunction_initialized = 2;
   }
}
void testfunction_trigger(void)
{

   //  Directly call user code, no parameters to pass
   extern void testfunction_PI_trigger(void);
   testfunction_PI_trigger();
   // puts ("testfunction_trigger called");
}

