#!/usr/bin/env python3

# File generated by asn2aadlPlus: DO NOT EDIT
from dmt.commonPy import aadlAST as ast

ast.g_signals = dict()

s = ast.Signal("dataview/dataview-uniq.asn", "DataItem", 8)
ast.g_signals["DataItem"] = s
ast.g_signals["DataView::DataItem"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "PID", 8)
ast.g_signals["PID"] = s
ast.g_signals["DataView::PID"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "PID-Range", 8)
ast.g_signals["PID_Range"] = s
ast.g_signals["DataView::PID_Range"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-Boolean", 8)
ast.g_signals["T_Boolean"] = s
ast.g_signals["DataView::T_Boolean"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-Int32", 8)
ast.g_signals["T_Int32"] = s
ast.g_signals["DataView::T_Int32"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-Int8", 8)
ast.g_signals["T_Int8"] = s
ast.g_signals["DataView::T_Int8"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-Null-Record", 0)
ast.g_signals["T_Null_Record"] = s
ast.g_signals["DataView::T_Null_Record"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-Runtime-Error", 16)
ast.g_signals["T_Runtime_Error"] = s
ast.g_signals["DataView::T_Runtime_Error"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-UInt32", 8)
ast.g_signals["T_UInt32"] = s
ast.g_signals["DataView::T_UInt32"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-UInt8", 8)
ast.g_signals["T_UInt8"] = s
ast.g_signals["DataView::T_UInt8"] = s
