#!/usr/bin/env python3

#  Automatically generated by kazoo/templates/glue/language_wrappers/mini-cv-python
#  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
#  This is an input file for the DMT tool "aadl2glueC". It is imported
#  at runtime and its role is to populate DMT's AST prior to executing the
#  B mapper functions.

from dmt.commonPy import aadlAST as ast

ast.g_apLevelContainers = dict()

# Interface "trigger"
sp = ast.ApLevelContainer("trigger")
ast.g_apLevelContainers["trigger"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::Interface_Cyclic_Offset = 0
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 1024
# Taste::InterfaceName = trigger
# Taste::RCMoperationKind = cyclic
# Taste::RCMperiod = 1000 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["trigger", "C", "C", "sender", sp._fpgaConfigurations])
sp._language = "C"

# Interface "ping"
sp = ast.ApLevelContainer("ping")
ast.g_apLevelContainers["ping"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::DataItem")
param._encoding = "ACN"
subProgramFeature = ast.AadlSubProgramFeature("param", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "DataItem"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("ping", "param", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("ping", "param", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Associated_Queue_Size = 1
# Taste::Communication_Layer = default
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 1024
# Taste::InterfaceName = ping
# Taste::labelInheritance = true
# Taste::RCMoperationKind = sporadic
# Taste::RCMperiod = 0 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["ping", "C", "C", "sender", sp._fpgaConfigurations])
sp._language = "C"

