/* Body file for function Receiver
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "receiver_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void receiver_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned receiver_initialized = 0;
void init_receiver(void)
{
   if (0 == receiver_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused __attribute__((unused)) = getTimeInMilliseconds();
      receiver_initialized = 1;
      // Call user code startup function
      extern void receiver_startup(void);
      receiver_startup();
      puts ("[TASTE] Initialization completed for function Receiver");
      receiver_initialized = 2;
   }
}
void receiver_ping
      (const char *IN_param, size_t IN_param_len)

{
   sender_pid = receiver_ping_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: receiver,ping,%lld\n", msc_time);
      fflush(stdout);
   }
   
   static asn1SccDataItem IN_PARAM;
   int param_error_code = 0;
   asn1SccDataItem_Initialize(&IN_PARAM);

   if (0 != Decode_ACN_DataItem (&IN_PARAM, (void *)IN_param, IN_param_len, &param_error_code)) {
      puts("Error decoding DataItem in function Receiver_ping");
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver_PI_ping
      (const asn1SccDataItem *);





   // Call user code
   receiver_PI_ping (&IN_PARAM);

}

